"""
Seed data: 100+ well-known companies across Greenhouse, Lever, and Ashby.
Covers tech, finance, consulting, and healthcare sectors.
"""

ATS_COMPANIES = [
    # ─── GREENHOUSE ───────────────────────────────────────────────────────────
    # Tech
    {"source": "GREENHOUSE", "slug": "airbnb",         "name": "Airbnb"},
    {"source": "GREENHOUSE", "slug": "stripe",          "name": "Stripe"},
    {"source": "GREENHOUSE", "slug": "databricks",      "name": "Databricks"},
    {"source": "GREENHOUSE", "slug": "figma",           "name": "Figma"},
    {"source": "GREENHOUSE", "slug": "notion",          "name": "Notion"},
    {"source": "GREENHOUSE", "slug": "discord",         "name": "Discord"},
    {"source": "GREENHOUSE", "slug": "twilio",          "name": "Twilio"},
    {"source": "GREENHOUSE", "slug": "zendesk",         "name": "Zendesk"},
    {"source": "GREENHOUSE", "slug": "elastic",         "name": "Elastic"},
    {"source": "GREENHOUSE", "slug": "hashicorp",       "name": "HashiCorp"},
    {"source": "GREENHOUSE", "slug": "cloudflare",      "name": "Cloudflare"},
    {"source": "GREENHOUSE", "slug": "mongodb",         "name": "MongoDB"},
    {"source": "GREENHOUSE", "slug": "confluent",       "name": "Confluent"},
    {"source": "GREENHOUSE", "slug": "amplitude",       "name": "Amplitude"},
    {"source": "GREENHOUSE", "slug": "segment",         "name": "Segment"},
    {"source": "GREENHOUSE", "slug": "brex",            "name": "Brex"},
    {"source": "GREENHOUSE", "slug": "rippling",        "name": "Rippling"},
    {"source": "GREENHOUSE", "slug": "lattice",         "name": "Lattice"},
    {"source": "GREENHOUSE", "slug": "gusto",           "name": "Gusto"},
    {"source": "GREENHOUSE", "slug": "chime",           "name": "Chime"},
    # Finance
    {"source": "GREENHOUSE", "slug": "coinbase",        "name": "Coinbase"},
    {"source": "GREENHOUSE", "slug": "robinhood",       "name": "Robinhood"},
    {"source": "GREENHOUSE", "slug": "plaid",           "name": "Plaid"},
    {"source": "GREENHOUSE", "slug": "affirm",          "name": "Affirm"},
    {"source": "GREENHOUSE", "slug": "marqeta",         "name": "Marqeta"},
    # Healthcare / BioTech
    {"source": "GREENHOUSE", "slug": "hims",            "name": "Hims & Hers"},
    {"source": "GREENHOUSE", "slug": "teladoc",         "name": "Teladoc Health"},
    {"source": "GREENHOUSE", "slug": "modernhealth",    "name": "Modern Health"},
    {"source": "GREENHOUSE", "slug": "collectivehealth","name": "Collective Health"},
    {"source": "GREENHOUSE", "slug": "flatiron",        "name": "Flatiron Health"},
    # Consulting / Enterprise
    {"source": "GREENHOUSE", "slug": "klaviyo",         "name": "Klaviyo"},
    {"source": "GREENHOUSE", "slug": "gong",            "name": "Gong"},
    {"source": "GREENHOUSE", "slug": "outreach",        "name": "Outreach"},
    {"source": "GREENHOUSE", "slug": "salesloft",       "name": "Salesloft"},
    {"source": "GREENHOUSE", "slug": "mixpanel",        "name": "Mixpanel"},

    # ─── LEVER ───────────────────────────────────────────────────────────────
    # Tech
    {"source": "LEVER", "slug": "netflix",             "name": "Netflix"},
    {"source": "LEVER", "slug": "netflix-is",          "name": "Netflix (International)"},
    {"source": "LEVER", "slug": "square",              "name": "Block (Square)"},
    {"source": "LEVER", "slug": "dropbox",             "name": "Dropbox"},
    {"source": "LEVER", "slug": "lyft",                "name": "Lyft"},
    {"source": "LEVER", "slug": "reddit",              "name": "Reddit"},
    {"source": "LEVER", "slug": "pinterest",           "name": "Pinterest"},
    {"source": "LEVER", "slug": "snap",                "name": "Snap"},
    {"source": "LEVER", "slug": "duolingo",            "name": "Duolingo"},
    {"source": "LEVER", "slug": "canva",               "name": "Canva"},
    {"source": "LEVER", "slug": "atlassian",           "name": "Atlassian"},
    {"source": "LEVER", "slug": "hubspot",             "name": "HubSpot"},
    {"source": "LEVER", "slug": "zendesk-2",           "name": "Zendesk (Lever)"},
    {"source": "LEVER", "slug": "asana",               "name": "Asana"},
    {"source": "LEVER", "slug": "intercom",            "name": "Intercom"},
    {"source": "LEVER", "slug": "cloudkitchens",       "name": "CloudKitchens"},
    {"source": "LEVER", "slug": "thumbtack",           "name": "Thumbtack"},
    {"source": "LEVER", "slug": "offerpad",            "name": "Offerpad"},
    {"source": "LEVER", "slug": "coursera",            "name": "Coursera"},
    {"source": "LEVER", "slug": "udemy",               "name": "Udemy"},
    # Finance
    {"source": "LEVER", "slug": "nerdwallet",          "name": "NerdWallet"},
    {"source": "LEVER", "slug": "betterment",          "name": "Betterment"},
    {"source": "LEVER", "slug": "wealthfront",         "name": "Wealthfront"},
    {"source": "LEVER", "slug": "fundrise",            "name": "Fundrise"},
    {"source": "LEVER", "slug": "greenlight",          "name": "Greenlight"},
    # Healthcare
    {"source": "LEVER", "slug": "one-medical",         "name": "One Medical"},
    {"source": "LEVER", "slug": "oscar",               "name": "Oscar Health"},
    {"source": "LEVER", "slug": "cityblock",           "name": "Cityblock Health"},
    {"source": "LEVER", "slug": "ro",                  "name": "Ro"},
    {"source": "LEVER", "slug": "zocdoc",              "name": "Zocdoc"},
    # Consulting / Enterprise
    {"source": "LEVER", "slug": "carta",               "name": "Carta"},
    {"source": "LEVER", "slug": "ironclad",            "name": "Ironclad"},
    {"source": "LEVER", "slug": "benchling",           "name": "Benchling"},
    {"source": "LEVER", "slug": "retool",              "name": "Retool"},
    {"source": "LEVER", "slug": "hex",                 "name": "Hex"},

    # ─── ASHBY ───────────────────────────────────────────────────────────────
    # Tech / AI
    {"source": "ASHBY", "slug": "anthropic",           "name": "Anthropic"},
    {"source": "ASHBY", "slug": "openai",              "name": "OpenAI"},
    {"source": "ASHBY", "slug": "mistral",             "name": "Mistral AI"},
    {"source": "ASHBY", "slug": "cohere",              "name": "Cohere"},
    {"source": "ASHBY", "slug": "perplexity",          "name": "Perplexity AI"},
    {"source": "ASHBY", "slug": "anyscale",            "name": "Anyscale"},
    {"source": "ASHBY", "slug": "modal",               "name": "Modal"},
    {"source": "ASHBY", "slug": "replit",              "name": "Replit"},
    {"source": "ASHBY", "slug": "linear",              "name": "Linear"},
    {"source": "ASHBY", "slug": "vercel",              "name": "Vercel"},
    {"source": "ASHBY", "slug": "supabase",            "name": "Supabase"},
    {"source": "ASHBY", "slug": "planetscale",         "name": "PlanetScale"},
    {"source": "ASHBY", "slug": "neon",                "name": "Neon"},
    {"source": "ASHBY", "slug": "fly",                 "name": "Fly.io"},
    {"source": "ASHBY", "slug": "grafana",             "name": "Grafana Labs"},
    {"source": "ASHBY", "slug": "temporal",            "name": "Temporal"},
    {"source": "ASHBY", "slug": "dbt-labs",            "name": "dbt Labs"},
    {"source": "ASHBY", "slug": "hex",                 "name": "Hex"},
    {"source": "ASHBY", "slug": "dagster",             "name": "Dagster"},
    {"source": "ASHBY", "slug": "prefect",             "name": "Prefect"},
    # Finance / Fintech
    {"source": "ASHBY", "slug": "mercury",             "name": "Mercury"},
    {"source": "ASHBY", "slug": "ramp",                "name": "Ramp"},
    {"source": "ASHBY", "slug": "moderntreasury",      "name": "Modern Treasury"},
    {"source": "ASHBY", "slug": "column",              "name": "Column"},
    {"source": "ASHBY", "slug": "slope",               "name": "Slope"},
    # Healthcare / BioTech
    {"source": "ASHBY", "slug": "genomics",            "name": "Color Genomics"},
    {"source": "ASHBY", "slug": "waymark",             "name": "Waymark"},
    {"source": "ASHBY", "slug": "turquoise",           "name": "Turquoise Health"},
    {"source": "ASHBY", "slug": "medable",             "name": "Medable"},
    {"source": "ASHBY", "slug": "sagewell",            "name": "Sagewell Financial"},
    # Consulting / Enterprise / Tools
    {"source": "ASHBY", "slug": "clerk",               "name": "Clerk"},
    {"source": "ASHBY", "slug": "resend",              "name": "Resend"},
    {"source": "ASHBY", "slug": "inngest",             "name": "Inngest"},
    {"source": "ASHBY", "slug": "trigger",             "name": "Trigger.dev"},
    {"source": "ASHBY", "slug": "calcom",              "name": "Cal.com"},
]
